version: "3"
services:
    rosetta:
        container_name: rosetta
        hostname: rosetta
        restart: unless-stopped
        image: rosetta
        build:
            context: .
            args:
                docker_gid: ${DOCKER_GID:-998}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - archives:/rosetta/archives
            - genki_media:/genki/media
        env_file:
          - .env
        networks:
          - genki_frau
volumes:
    archives:
    genki_media:
        external: true
networks:
    genki_frau:
        external: true
