version: "3"
services:
    rosetta:
        container_name: rosetta
        hostname: rosetta
        restart: unless-stopped
        image: rosetta
        build:
            context: .
        env_file:
            - .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - archives:/rosetta/archives
            - genki_media:/genki/media
volumes:
    archives:
    genki_media:
        external: true
networks:
    default:
        driver: bridge
        driver_opts: 
            com.docker.network.bridge.name: rosetta
        ipam:
            driver: default
            config:
                - subnet: 172.40.0.0/16
