[tool.poetry]
name = "rosetta"
version = "0.1.0"
description = "Discord bot for managing channels in playthrough servers."
authors = ["Rain <Rain#8710>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.0"
"discord.py" = "^1.4.1"
genki = {path = "../genki", develop = true}
docker = "^4.3.1"


[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
black = "^19.10b0"
flake8 = "^3.8.1"
rope = "^0.17.0"

[tool.poetry.scripts]
config = "scripts:config"
start = "scripts:start"
test = "scripts:test"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
